version: '3.4'

services:
  phoneservice.api:
    hostname: phone_service_api
    ports:
    - 5009:8080
    image: ${DOCKER_REGISTRY-}phoneserviceapi
    build:
      context: .
      dockerfile: PhoneService.Api/Dockerfile

  PhoneService.LoadTests:
    hostname: phoneService_LoadTests
    ports:
    - 5012:8080 
    image: ${DOCKER_REGISTRY-}phoneserviceloadtests
    build:
      context: .
      dockerfile: PhoneService.LoadTests/Dockerfile
    environment:
        PhoneServiceApiUrl: ${PhoneServiceApiUrl}
        
  PhoneService.Front:
    hostname: phoneService_Front
    ports:
    - 5013:3000
    image: ${DOCKER_REGISTRY-}phoneservicefront
    build:
      context: .
      dockerfile: phone_service_front/Dockerfile
      args:
        MAIN_HOST_API: 'http://localhost:5009'
        LOADTEST_HOST_API: 'http://localhost:5012'
    restart: always

